export const SYSTEM_ICON_OPTIONS = [
  { label: "Aplicativos", value: "fa-table-cells" },
  { label: "Prédio", value: "fa-building" },
  { label: "Diagrama", value: "fa-diagram-project" },
  { label: "Identidade", value: "fa-id-card" },
  { label: "Gráfico", value: "fa-chart-line" },
  { label: "Caminhão", value: "fa-truck" },
  { label: "Moedas", value: "fa-coins" },
  { label: "Loja", value: "fa-store" },
  { label: "Usuário", value: "fa-user-plus" },
  { label: "Infinito", value: "fa-infinity" },
  { label: "Bússola", value: "fa-compass" },
  { label: "Pulso", value: "fa-heart-pulse" },
  { label: "Servidor", value: "fa-server" },
  { label: "Nuvem", value: "fa-cloud" },
  { label: "Globo", value: "fa-globe" },
  { label: "Janela", value: "fa-window-restore" },
  { label: "Engrenagem", value: "fa-gears" },
  { label: "Pasta", value: "fa-folder-open" },
  { label: "Maleta", value: "fa-briefcase" },
  { label: "Cadeado", value: "fa-lock" },
] as const;
