import type { LoopDataset } from "./types";

const today = new Date();
function daysFromNow(offset: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + offset);
  return d.toISOString().slice(0, 10);
}

function daysAgo(offset: number): string {
  return daysFromNow(-offset);
}

export const LOOP_MOCK_DATA: LoopDataset = {
  people: [
    { id: "p-juliana", name: "Juliana Costa", role: "Product Owner", area: "RH" },
    { id: "p-ricardo", name: "Ricardo Alencar", role: "Tech Lead", area: "TI" },
    { id: "p-mariana", name: "Mariana Silva", role: "Analista de Automação", area: "TI" },
    { id: "p-felipe", name: "Felipe Andrade", role: "BI Analyst", area: "Operações" },
    { id: "p-leonardo", name: "Leonardo Mendes", role: "Diretor de TI", area: "TI" },
    { id: "p-camila", name: "Camila Rocha", role: "Gerente de Projetos", area: "PMO" },
    { id: "p-andre", name: "André Souza", role: "Arquiteto de Soluções", area: "TI" },
    { id: "p-patricia", name: "Patrícia Lima", role: "Head de RH", area: "RH" },
  ],
  teams: [
    {
      id: "team-ti",
      name: "TI",
      description: "Desenvolvimento, infraestrutura e suporte",
      managerId: "p-leonardo",
      capacityHours: 1600,
      availableHours: 1200,
      allocatedHours: 1360,
      memberCount: 18,
      projectCount: 4,
      openActivities: 42,
    },
    {
      id: "team-rh",
      name: "RH",
      description: "Recursos humanos e jornada do colaborador",
      managerId: "p-patricia",
      capacityHours: 800,
      availableHours: 640,
      allocatedHours: 576,
      memberCount: 8,
      projectCount: 2,
      openActivities: 18,
    },
    {
      id: "team-ops",
      name: "Operações",
      description: "Processos e analytics operacional",
      managerId: "p-felipe",
      capacityHours: 960,
      availableHours: 720,
      allocatedHours: 864,
      memberCount: 10,
      projectCount: 2,
      openActivities: 24,
    },
    {
      id: "team-comercial",
      name: "Comercial",
      description: "Vendas e relacionamento",
      managerId: "p-camila",
      capacityHours: 640,
      availableHours: 560,
      allocatedHours: 416,
      memberCount: 6,
      projectCount: 1,
      openActivities: 12,
    },
  ],
  projects: [
    {
      id: "proj-portal-rh",
      code: "PRH-20",
      name: "Portal RH 2.0",
      description: "Nova experiência digital para colaboradores",
      objective: "Modernizar jornada RH com holerite, férias e benefícios integrados",
      status: "em_andamento",
      health: "atencao",
      priority: "alta",
      criticality: "alta",
      startDate: daysAgo(90),
      plannedEndDate: daysFromNow(45),
      progress: 72,
      ownerId: "p-juliana",
      teamId: "team-rh",
      sponsorId: "p-patricia",
      isActive: true,
    },
    {
      id: "proj-intranet",
      code: "INT-01",
      name: "Intranet Corporativa",
      description: "Hub unificado de comunicação interna",
      objective: "Centralizar comunicados, documentos e serviços",
      status: "execucao",
      health: "no_prazo",
      priority: "alta",
      criticality: "media",
      startDate: daysAgo(120),
      plannedEndDate: daysFromNow(60),
      progress: 58,
      ownerId: "p-ricardo",
      teamId: "team-ti",
      sponsorId: "p-leonardo",
      isActive: true,
    },
    {
      id: "proj-rpa",
      code: "RPA-03",
      name: "Automação de Processos",
      description: "Bots RPA para rotinas operacionais",
      objective: "Reduzir trabalho manual em compras e financeiro",
      status: "atencao",
      health: "critico",
      priority: "alta",
      criticality: "alta",
      startDate: daysAgo(60),
      plannedEndDate: daysFromNow(30),
      progress: 31,
      ownerId: "p-mariana",
      teamId: "team-ti",
      sponsorId: "p-leonardo",
      isActive: true,
    },
    {
      id: "proj-analytics",
      code: "ANA-07",
      name: "Analytics Operacional",
      description: "Dashboards executivos e KPIs",
      objective: "Visibilidade em tempo real da operação",
      status: "revisao",
      health: "atencao",
      priority: "media",
      criticality: "media",
      startDate: daysAgo(75),
      plannedEndDate: daysFromNow(20),
      progress: 64,
      ownerId: "p-felipe",
      teamId: "team-ops",
      sponsorId: "p-camila",
      isActive: true,
    },
    {
      id: "proj-app-colab",
      code: "APP-12",
      name: "App do Colaborador",
      description: "Aplicativo mobile corporativo",
      objective: "Acesso mobile a serviços e comunicação",
      status: "planejamento",
      health: "no_prazo",
      priority: "media",
      criticality: "baixa",
      startDate: daysFromNow(7),
      plannedEndDate: daysFromNow(120),
      progress: 12,
      ownerId: "p-andre",
      teamId: "team-ti",
      sponsorId: "p-leonardo",
      isActive: true,
    },
    {
      id: "proj-cloud",
      code: "CLD-05",
      name: "Migração para Nuvem",
      description: "Migração de workloads para Azure",
      objective: "Modernizar infraestrutura e reduzir custos",
      status: "em_andamento",
      health: "no_prazo",
      priority: "alta",
      criticality: "alta",
      startDate: daysAgo(45),
      plannedEndDate: daysFromNow(90),
      progress: 45,
      ownerId: "p-andre",
      teamId: "team-ti",
      sponsorId: "p-leonardo",
      isActive: true,
    },
  ],
  phases: [
    { id: "ph-1", projectId: "proj-portal-rh", name: "Planejamento", type: "planejamento", startDate: daysAgo(90), endDate: daysAgo(60), progress: 100, status: "concluido", color: "#6366f1", sequence: 1 },
    { id: "ph-2", projectId: "proj-portal-rh", name: "Execução", type: "execucao", startDate: daysAgo(59), endDate: daysFromNow(15), progress: 75, status: "em_andamento", color: "#0ea5e9", sequence: 2 },
    { id: "ph-3", projectId: "proj-portal-rh", name: "Revisão", type: "revisao", startDate: daysFromNow(16), endDate: daysFromNow(30), progress: 0, status: "pendente", color: "#f59e0b", sequence: 3 },
    { id: "ph-4", projectId: "proj-portal-rh", name: "Entrega", type: "entrega", startDate: daysFromNow(31), endDate: daysFromNow(45), progress: 0, status: "pendente", color: "#10b981", sequence: 4 },
    { id: "ph-5", projectId: "proj-intranet", name: "Planejamento", type: "planejamento", startDate: daysAgo(120), endDate: daysAgo(90), progress: 100, status: "concluido", color: "#6366f1", sequence: 1 },
    { id: "ph-6", projectId: "proj-intranet", name: "Execução", type: "execucao", startDate: daysAgo(89), endDate: daysFromNow(30), progress: 60, status: "em_andamento", color: "#0ea5e9", sequence: 2 },
    { id: "ph-7", projectId: "proj-rpa", name: "Planejamento", type: "planejamento", startDate: daysAgo(60), endDate: daysAgo(40), progress: 100, status: "concluido", color: "#6366f1", sequence: 1 },
    { id: "ph-8", projectId: "proj-rpa", name: "Execução", type: "execucao", startDate: daysAgo(39), endDate: daysFromNow(10), progress: 35, status: "atrasado", color: "#0ea5e9", sequence: 2 },
    { id: "ph-9", projectId: "proj-analytics", name: "Execução", type: "execucao", startDate: daysAgo(75), endDate: daysFromNow(5), progress: 80, status: "em_andamento", color: "#0ea5e9", sequence: 1 },
    { id: "ph-10", projectId: "proj-analytics", name: "Revisão", type: "revisao", startDate: daysFromNow(6), endDate: daysFromNow(20), progress: 10, status: "pendente", color: "#f59e0b", sequence: 2 },
    { id: "ph-11", projectId: "proj-cloud", name: "Planejamento", type: "planejamento", startDate: daysAgo(45), endDate: daysAgo(20), progress: 100, status: "concluido", color: "#6366f1", sequence: 1 },
    { id: "ph-12", projectId: "proj-cloud", name: "Execução", type: "execucao", startDate: daysAgo(19), endDate: daysFromNow(60), progress: 40, status: "em_andamento", color: "#0ea5e9", sequence: 2 },
  ],
  milestones: [
    { id: "ms-1", projectId: "proj-portal-rh", phaseId: "ph-2", name: "Homologação RH", description: "Validação com stakeholders", plannedDate: daysFromNow(10), status: "pendente", criticality: "alta" },
    { id: "ms-2", projectId: "proj-portal-rh", phaseId: "ph-4", name: "Go-live", description: "Lançamento produção", plannedDate: daysFromNow(45), status: "pendente", criticality: "alta" },
    { id: "ms-3", projectId: "proj-intranet", phaseId: "ph-6", name: "Revisão executiva", description: "Aprovação diretoria", plannedDate: daysFromNow(25), status: "pendente", criticality: "media" },
    { id: "ms-4", projectId: "proj-rpa", phaseId: "ph-8", name: "Piloto compras", description: "Bot em ambiente piloto", plannedDate: daysAgo(3), status: "atrasado", criticality: "alta" },
    { id: "ms-5", projectId: "proj-analytics", phaseId: "ph-9", name: "Dashboard operacional", description: "Entrega MVP dashboards", plannedDate: daysFromNow(5), status: "pendente", criticality: "media" },
    { id: "ms-6", projectId: "proj-cloud", phaseId: "ph-12", name: "Migração fase 1", description: "Apps críticos na nuvem", plannedDate: daysFromNow(40), status: "pendente", criticality: "alta" },
  ],
  activities: [
    { id: "act-1", projectId: "proj-portal-rh", title: "Revisar requisitos de integração", description: "Mapear APIs TOTVS", assigneeId: "p-juliana", teamId: "team-rh", status: "em_andamento", priority: "alta", criticality: "media", startDate: daysAgo(5), dueDate: daysFromNow(2), progress: 60, estimatedHours: 16, actualHours: 10 },
    { id: "act-2", projectId: "proj-intranet", title: "Homologar novo fluxo de aprovações", description: "Validar workflow", assigneeId: "p-ricardo", teamId: "team-ti", status: "pendente", priority: "alta", criticality: "alta", startDate: daysAgo(2), dueDate: daysFromNow(3), progress: 0, estimatedHours: 24, actualHours: 0 },
    { id: "act-3", projectId: "proj-rpa", title: "Testes de automação RPA", description: "Cenários de compras", assigneeId: "p-mariana", teamId: "team-ti", status: "em_andamento", priority: "alta", criticality: "alta", startDate: daysAgo(7), dueDate: daysFromNow(2), progress: 45, estimatedHours: 32, actualHours: 18, blocker: "Ambiente piloto indisponível" },
    { id: "act-4", projectId: "proj-analytics", title: "Validar dashboard operacional", description: "Revisão com gestores", assigneeId: "p-felipe", teamId: "team-ops", status: "pendente", priority: "media", criticality: "media", startDate: daysAgo(1), dueDate: daysFromNow(6), progress: 0, estimatedHours: 12, actualHours: 0 },
    { id: "act-5", projectId: "proj-portal-rh", title: "Implementar módulo férias", description: "Frontend + API", assigneeId: "p-juliana", teamId: "team-rh", status: "em_andamento", priority: "alta", criticality: "media", startDate: daysAgo(14), dueDate: daysFromNow(10), progress: 70, estimatedHours: 40, actualHours: 28 },
    { id: "act-6", projectId: "proj-intranet", title: "Migrar comunicados legados", description: "Importação em massa", assigneeId: "p-ricardo", teamId: "team-ti", status: "em_andamento", priority: "media", criticality: "baixa", startDate: daysAgo(10), dueDate: daysFromNow(8), progress: 55, estimatedHours: 20, actualHours: 12 },
    { id: "act-7", projectId: "proj-rpa", title: "Documentar processos AS-IS", description: "Mapeamento BPMN", assigneeId: "p-mariana", teamId: "team-ti", status: "concluida", priority: "media", criticality: "baixa", startDate: daysAgo(30), dueDate: daysAgo(5), completedAt: daysAgo(6), progress: 100, estimatedHours: 16, actualHours: 14 },
    { id: "act-8", projectId: "proj-analytics", title: "Conectar fonte ERP", description: "ETL TOTVS", assigneeId: "p-felipe", teamId: "team-ops", status: "bloqueada", priority: "alta", criticality: "alta", startDate: daysAgo(8), dueDate: daysAgo(2), progress: 30, estimatedHours: 24, actualHours: 8, blocker: "Credenciais API pendentes" },
    { id: "act-9", projectId: "proj-cloud", title: "Provisionar ambiente Azure", description: "IaC Terraform", assigneeId: "p-andre", teamId: "team-ti", status: "em_andamento", priority: "alta", criticality: "alta", startDate: daysAgo(12), dueDate: daysFromNow(5), progress: 50, estimatedHours: 48, actualHours: 24 },
    { id: "act-10", projectId: "proj-app-colab", title: "Definir escopo MVP", description: "Workshop com stakeholders", assigneeId: "p-andre", teamId: "team-ti", status: "planejada", priority: "media", criticality: "baixa", startDate: daysFromNow(7), dueDate: daysFromNow(14), progress: 0, estimatedHours: 8, actualHours: 0 },
    { id: "act-11", projectId: "proj-portal-rh", title: "Testes de regressão holerite", description: "QA automatizado", assigneeId: "p-juliana", teamId: "team-rh", status: "em_revisao", priority: "alta", criticality: "media", startDate: daysAgo(3), dueDate: daysFromNow(1), progress: 90, estimatedHours: 16, actualHours: 14 },
    { id: "act-12", projectId: "proj-intranet", title: "Configurar SSO corporativo", description: "Integração Azure AD", assigneeId: "p-ricardo", teamId: "team-ti", status: "concluida", priority: "alta", criticality: "alta", startDate: daysAgo(20), dueDate: daysAgo(8), completedAt: daysAgo(9), progress: 100, estimatedHours: 32, actualHours: 30 },
    { id: "act-13", projectId: "proj-rpa", title: "Treinamento equipe compras", description: "Capacitação usuários", assigneeId: "p-mariana", teamId: "team-ti", status: "pendente", priority: "baixa", criticality: "baixa", startDate: daysFromNow(5), dueDate: daysFromNow(15), progress: 0, estimatedHours: 8, actualHours: 0 },
    { id: "act-14", projectId: "proj-analytics", title: "Criar relatório executivo", description: "PDF automático semanal", assigneeId: "p-felipe", teamId: "team-ops", status: "em_andamento", priority: "media", criticality: "media", startDate: daysAgo(6), dueDate: daysFromNow(4), progress: 40, estimatedHours: 20, actualHours: 8 },
    { id: "act-15", projectId: "proj-cloud", title: "Inventário de servidores", description: "Levantamento on-prem", assigneeId: "p-andre", teamId: "team-ti", status: "concluida", priority: "alta", criticality: "media", startDate: daysAgo(40), dueDate: daysAgo(25), completedAt: daysAgo(26), progress: 100, estimatedHours: 24, actualHours: 22 },
  ],
  risks: [
    { id: "risk-1", projectId: "proj-rpa", title: "Atraso no ambiente piloto", description: "Infra não liberou ambiente RPA", category: "Técnico", probability: 4, impact: 4, severity: "alto", status: "aberto", ownerId: "p-mariana", mitigationPlan: "Escalar para infra e definir ambiente alternativo", dueDate: daysFromNow(5) },
    { id: "risk-2", projectId: "proj-portal-rh", title: "Dependência API TOTVS", description: "Endpoints instáveis em homologação", category: "Integração", probability: 3, impact: 4, severity: "alto", status: "aberto", ownerId: "p-juliana", mitigationPlan: "Mock layer e contrato de SLA com fornecedor", dueDate: daysFromNow(10) },
    { id: "risk-3", projectId: "proj-analytics", title: "Qualidade dos dados ERP", description: "Inconsistências no cadastro", category: "Dados", probability: 4, impact: 3, severity: "medio", status: "aberto", ownerId: "p-felipe", mitigationPlan: "Data cleansing antes do go-live", dueDate: daysFromNow(7) },
    { id: "risk-4", projectId: "proj-intranet", title: "Resistência à mudança", description: "Usuários acostumados ao legado", category: "Organizacional", probability: 3, impact: 3, severity: "medio", status: "mitigado", ownerId: "p-ricardo", mitigationPlan: "Programa de change management", dueDate: daysFromNow(20) },
    { id: "risk-5", projectId: "proj-cloud", title: "Estouro de orçamento cloud", description: "Custos acima do previsto", category: "Financeiro", probability: 2, impact: 5, severity: "alto", status: "aberto", ownerId: "p-andre", mitigationPlan: "FinOps e alertas de custo", dueDate: daysFromNow(30) },
    { id: "risk-6", projectId: "proj-rpa", title: "Falta de documentação processos", description: "Processos não padronizados", category: "Processo", probability: 3, impact: 3, severity: "medio", status: "fechado", ownerId: "p-mariana", mitigationPlan: "Workshops de mapeamento", dueDate: daysAgo(10) },
    { id: "risk-7", projectId: "proj-portal-rh", title: "Turnover na equipe", description: "Desenvolvedor sênior em processo de saída", category: "Recursos", probability: 2, impact: 4, severity: "medio", status: "aberto", ownerId: "p-juliana", mitigationPlan: "Knowledge transfer e contratação", dueDate: daysFromNow(15) },
    { id: "risk-8", projectId: "proj-analytics", title: "Escopo creep", description: "Novos KPIs solicitados sem priorização", category: "Escopo", probability: 4, impact: 2, severity: "medio", status: "aberto", ownerId: "p-felipe", mitigationPlan: "Change control com PMO", dueDate: daysFromNow(12) },
    { id: "risk-9", projectId: "proj-intranet", title: "Performance em pico", description: "Lentidão em horários de pico", category: "Técnico", probability: 2, impact: 3, severity: "baixo", status: "aberto", ownerId: "p-ricardo", mitigationPlan: "Load testing e auto-scaling", dueDate: daysFromNow(25) },
    { id: "risk-10", projectId: "proj-cloud", title: "Compliance LGPD", description: "Dados sensíveis em nuvem", category: "Compliance", probability: 2, impact: 5, severity: "critico", status: "aberto", ownerId: "p-andre", mitigationPlan: "Revisão jurídica e DPA", dueDate: daysFromNow(20) },
    { id: "risk-11", projectId: "proj-app-colab", title: "Aprovação App Store", description: "Políticas de publicação", category: "Externo", probability: 2, impact: 2, severity: "baixo", status: "aberto", ownerId: "p-andre", mitigationPlan: "Pré-validação guidelines", dueDate: daysFromNow(60) },
    { id: "risk-12", projectId: "proj-rpa", title: "Manutenção bots", description: "Mudanças em sistemas legados", category: "Operacional", probability: 4, impact: 3, severity: "medio", status: "aberto", ownerId: "p-mariana", mitigationPlan: "Monitoramento proativo", dueDate: daysFromNow(45) },
  ],
  approvals: [
    { id: "appr-1", projectId: "proj-intranet", type: "Orçamento", title: "Orçamento — Intranet Corporativa", description: "Aprovação de budget adicional Q3", requesterId: "p-ricardo", approverId: "p-leonardo", priority: "alta", status: "pendente", requestedAt: daysAgo(5), dueDate: daysFromNow(3) },
    { id: "appr-2", projectId: "proj-rpa", type: "Escopo", title: "Escopo — Automação de Processos", description: "Inclusão módulo financeiro no escopo", requesterId: "p-mariana", approverId: "p-camila", priority: "media", status: "pendente", requestedAt: daysAgo(3), dueDate: daysFromNow(5) },
    { id: "appr-3", projectId: "proj-portal-rh", type: "Go-live", title: "Go-live Portal RH 2.0", description: "Autorização para produção", requesterId: "p-juliana", approverId: "p-patricia", priority: "alta", status: "pendente", requestedAt: daysAgo(2), dueDate: daysFromNow(10) },
    { id: "appr-4", projectId: "proj-cloud", type: "Infraestrutura", title: "Provisionamento Azure", description: "Aprovação de recursos cloud", requesterId: "p-andre", approverId: "p-leonardo", priority: "alta", status: "aprovado", requestedAt: daysAgo(15), dueDate: daysAgo(10), decidedAt: daysAgo(11), decisionReason: "Aprovado com limite de custo mensal" },
    { id: "appr-5", projectId: "proj-analytics", type: "Escopo", title: "Novos KPIs operacionais", description: "Expansão de indicadores", requesterId: "p-felipe", approverId: "p-camila", priority: "baixa", status: "devolvido", requestedAt: daysAgo(8), dueDate: daysAgo(3), decidedAt: daysAgo(4), decisionReason: "Priorizar MVP antes de novos KPIs" },
  ],
  deliverables: [
    { id: "del-1", projectId: "proj-portal-rh", milestoneId: "ms-1", name: "Módulo holerite", description: "Holerite digital integrado", plannedDate: daysFromNow(7), status: "pendente", responsibleId: "p-juliana" },
    { id: "del-2", projectId: "proj-portal-rh", milestoneId: "ms-2", name: "Portal RH produção", description: "Release completo", plannedDate: daysFromNow(45), status: "pendente", responsibleId: "p-juliana" },
    { id: "del-3", projectId: "proj-intranet", name: "Hub comunicados", description: "Módulo comunicados migrado", plannedDate: daysFromNow(14), status: "pendente", responsibleId: "p-ricardo" },
    { id: "del-4", projectId: "proj-rpa", milestoneId: "ms-4", name: "Bot compras piloto", description: "Automação em piloto", plannedDate: daysAgo(3), status: "atrasado", responsibleId: "p-mariana" },
    { id: "del-5", projectId: "proj-analytics", milestoneId: "ms-5", name: "Dashboard MVP", description: "Painel operacional", plannedDate: daysFromNow(5), status: "pendente", responsibleId: "p-felipe" },
    { id: "del-6", projectId: "proj-cloud", name: "Landing zone Azure", description: "Ambiente base configurado", plannedDate: daysFromNow(3), actualDate: daysAgo(1), status: "entregue", responsibleId: "p-andre" },
    { id: "del-7", projectId: "proj-intranet", name: "SSO corporativo", description: "Login único ativo", plannedDate: daysAgo(8), actualDate: daysAgo(9), status: "entregue", responsibleId: "p-ricardo" },
  ],
  lessons: [
    { id: "lesson-1", projectId: "proj-intranet", title: "Comunicação antecipada com stakeholders", description: "Reuniões semanais reduziram retrabalho em 30%", category: "Gestão", impact: "Alto", recommendation: "Manter ritual de status semanal desde o kick-off", createdBy: "p-ricardo", createdAt: daysAgo(10) },
    { id: "lesson-2", projectId: "proj-rpa", title: "Ambiente piloto é pré-requisito", description: "Atraso de 2 semanas por infra não provisionada", category: "Infraestrutura", impact: "Alto", recommendation: "Incluir provisionamento no planejamento da fase 1", createdBy: "p-mariana", createdAt: daysAgo(5) },
    { id: "lesson-3", projectId: "proj-portal-rh", title: "Integração TOTVS requer buffer", description: "APIs instáveis geraram retrabalho", category: "Integração", impact: "Médio", recommendation: "Reservar 20% do cronograma para integrações", createdBy: "p-juliana", createdAt: daysAgo(15) },
    { id: "lesson-4", projectId: "proj-analytics", title: "Data quality antes de dashboards", description: "Dashboards com dados sujos geram desconfiança", category: "Dados", impact: "Alto", recommendation: "Fase de cleansing obrigatória antes de visualizações", createdBy: "p-felipe", createdAt: daysAgo(8) },
    { id: "lesson-5", projectId: "proj-cloud", title: "FinOps desde o início", description: "Custos cloud precisam de governança early", category: "Financeiro", impact: "Médio", recommendation: "Definir budgets e alertas no provisionamento", createdBy: "p-andre", createdAt: daysAgo(20) },
  ],
  performanceHistory: [
    { referenceDate: daysAgo(28), value: 68 },
    { referenceDate: daysAgo(21), value: 70 },
    { referenceDate: daysAgo(14), value: 72 },
    { referenceDate: daysAgo(7), value: 75 },
    { referenceDate: today.toISOString().slice(0, 10), value: 78 },
  ],
};
